# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Leizhen Wang - Academic Website"
title_separator          : "-"
name                     : &name "Leizhen Wang (王雷震)"
description              : &description "PhD Candidate in Data Science and AI at Monash University"
url                      : "https://georgewanglz2019.github.io" # 修改为你的仓库 Pages 地址
baseurl                  : ""
repository               : "georgewanglz2019/georgewanglz2019.github.io" # 修改为你的 repo

# Site Author
author:
  avatar           : "LeizhenWang.png"
  name             : "Leizhen Wang"
  pronouns         : "he/him"
  bio              : "PhD Candidate in Data Science and Artificial Intelligence at Monash University. Research interests: Large Language Models, Reinforcement Learning, and Urban Transportation Systems."
  location         : "Melbourne, Australia"
  employer         : "Monash University"
  uri              : 
  email            : # 如果不想公开邮箱，可以留空

  # Academic websites
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=sM-HlFAAAAAJ&view_op=list_works&sortby=pubdate"
  orcid            : "https://orcid.org/0000-0001-6523-3057"
  researchgate     : "https://www.researchgate.net/profile/Leizhen-Wang-2?ev=hdr_xprf"
  scopus           : # 可留空

  # Repositories and software development
  github           : "georgewanglz2019"

  # Social media
  linkedin         : "https://www.linkedin.com/in/leizhen-wang-0766a8250/"
  twitter          : # 暂无可留空
  bluesky          : # 可删除
